
    create table categorias (
        id integer generated by default as identity,
        tipo integer,
        nome varchar(255),
        primary key (id)
    );

    create table orcamentos (
        data_fim date,
        data_inicio date,
        id integer generated by default as identity,
        usuario_id integer,
        valor float(53),
        nome varchar(255),
        primary key (id)
    );

    create table perfis (
        perfis integer,
        usuario_id integer not null
    );

    create table transacoes (
        categoria_id integer,
        data date,
        id integer generated by default as identity,
        orcamento_id integer,
        usuario_id integer,
        valor float(53),
        descricao varchar(255),
        primary key (id)
    );

    create table usuarios (
        id integer generated by default as identity,
        email varchar(255) unique,
        nome varchar(255),
        senha varchar(255),
        primary key (id)
    );

    alter table if exists orcamentos 
       add constraint FKqglev9uveaiftbxu0q958jky2 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists perfis 
       add constraint FK4khnbs8y5xgijftx9c34bbpg 
       foreign key (usuario_id) 
       references usuarios;

    alter table if exists transacoes 
       add constraint FKpo0f1uru9p0eagc24edw76mw8 
       foreign key (categoria_id) 
       references categorias;

    alter table if exists transacoes 
       add constraint FKrhfo959l1y3pi7ke0tldrouo8 
       foreign key (orcamento_id) 
       references orcamentos;

    alter table if exists transacoes 
       add constraint FKkcpkacordh1eujovjxlgdmhcx 
       foreign key (usuario_id) 
       references usuarios;
